Implementation of authentication without password step
believerfenix/bookstore_rg pull request #12
Opened 2022-06-08 20:39 UTC by believerfenix

2022-07-09 13:28 UTC, ElenaSokolyk requested changes

2022-07-09 13:28 UTC, ElenaSokolyk commented on app/views/checkouts/show.html.haml
> +  %h1.general-title-margin Checkout
do you need this hardcoded template?

2022-07-09 13:28 UTC, ElenaSokolyk commented on app/services/quick_registrations/quick_registrations_service.rb
> +  class QuickRegistrationsService < BaseService
name looks weird, with duplications - QuickRegistrations:: QuickRegistrationsService. you can either remove module or change names of module or class.

2022-07-17 13:39 UTC, believerfenix commented on app/views/checkouts/show.html.haml
> +  %h1.general-title-margin Checkout
this is the template that is given with the task. Further implementation and logic of this page will be in the next step

2022-07-20 09:36 UTC, ElenaSokolyk approved these changes

2022-07-20 10:42 UTC, merged